name: Merge Pull Request Automation

on: 
  pull_request:
    types: [ labeled, edited, unlabeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'automerge' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Get current PR Number
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
