name: Merge Pull Request Automation

on: 
  pull_request:
    types: 
      - labeled
      - edited
      - unlabeled

jobs:
  build:
    if: ${{ github.event.label.name == 'automerge' }}
    runs-on: ubuntu-latest
    env: 
      GITHUB_REF: ${{ github.ref }}
      PR_NUMBER: ${{github.event.number}}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: $GITHUB_REF
          run: |
            echo "Reference is $GITHUB_REF"
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: $PR_NUMBER
          run: |
            echo "PR Number is $PR_NUMBER"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
